services:
  q3js-master-server:
    container_name: q3js-master-server
    build: build/master-server
    ports:
      - 27950:27950
    volumes:
      - ./config/certificates:/app/certificates:ro

  q3js-content-server:
    container_name: q3js-content-server
    build: build/content-server
    ports:
      - 9000:9000
    volumes:
      - ./assets:/app/assets:rw
      - ./config/certificates:/app/certificates:ro

  q3js-web-client:
    container_name: q3js-web-client
    build: build/web-client
    env_file: .env
    depends_on:
      - q3js-content-server
    ports:
      - 443:443
    volumes:
      - ./index.ejs:/app/bin/index.ejs:ro
      - ./config/certificates:/app/certificates:ro

  q3js-dedicated-server-1:
    container_name: q3js-dedicated-server-1
    build: build/dedicated-server
    env_file: .env
    depends_on:
      - q3js-content-server
    volumes:
      - ./config/dedicated-server/baseq3/server.cfg:/app/base/baseq3/server.cfg
      - ./config/dedicated-server/cpma/server.cfg:/app/base/cpma/server.cfg

  q3js-ds-wss-proxy-1:
    container_name: q3js-ds-wss-proxy-1
    build: build/wss-proxy
    depends_on:
      - q3js-dedicated-server-1
    ports:
      - 27961:27961
    environment:
      Q3JS_WSS_PROXY_ADDRESS: q3js-dedicated-server-1
      Q3JS_WSS_PROXY_PORT: 27960
      Q3JS_WSS_PORT: 27961
    volumes:
      - ./config/certificates:/app/certificates:ro

  q3js-dedicated-server-2:
    container_name: q3js-dedicated-server-2
    build: build/dedicated-server
    env_file: .env
    depends_on:
      - q3js-content-server
    volumes:
      - ./config/dedicated-server/baseq3/server.cfg:/app/base/baseq3/server.cfg
      - ./config/dedicated-server/cpma/server.cfg:/app/base/cpma/server.cfg

  q3js-ds-wss-proxy-2:
    container_name: q3js-ds-wss-proxy-2
    build: build/wss-proxy
    depends_on:
      - q3js-dedicated-server-2
    ports:
      - 27962:27962
    environment:
      Q3JS_WSS_PROXY_ADDRESS: q3js-dedicated-server-2
      Q3JS_WSS_PROXY_PORT: 27960
      Q3JS_WSS_PORT: 27962
    volumes:
      - ./config/certificates:/app/certificates:ro
